function data = importfile(fileToRead)
    %IMPORTFILE1(FILETOREAD1)
    %  Imports data from the specified file
    %  FILETOREAD1:  file to read

    %  Auto-generated by MATLAB on 24-Jun-2013 16:19:12

    % Import the file
    newData = importdata(fileToRead);

    % % Create new variables in the base workspace from those fields.
    if isfield(newData, 'colheaders') 
        for i = 1:size(newData.colheaders, 2)
            assignin('caller', genvarname(newData.colheaders{i}), newData.data(:,i));
            if isfield(newData, 'data') 
                data.(genvarname(newData.colheaders{i}))= newData.data(:,i);
            else
                data = [];
            end
        end
        if isfield(data, 'time_s') && isfield(data, 'time_us')
            data.Time = (data.time_s-data.time_s(1)) + (data.time_us-data.time_us(1))/1e+6;
        else
            data = [];
        end
    else
        data = [];
    end
end

