function cellInfo = busobjects(varargin) 
% BUSOBJECTS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'SChannel', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'arCChannel', 1, 'arCChannel_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'SCommand', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'arCPath', 1, 'arCPath_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arCPos', 1, 'arCPos_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arCAttQuat', 1, 'arCAttQuat_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'rCTurnRate', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'SNav', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'arNAcc', 1, 'arNAcc_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'argNVel', 1, 'argNVel_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arNRate', 1, 'arNRate_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'argNPos', 1, 'argNPos_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arNQuat', 1, 'arNQuat_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arNHeight', 1, 'arNHeight_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arWGS84', 1, 'arWGS84_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arNAirData', 1, 'arNAirData_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arNVel', 1, 'arNVel_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'arNEuler', 1, 'arNEuler_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'STask', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'iTControlFlag', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'iTControlFlagX', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'iTControlFlagY', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'iTControlFlagZ', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'iTControlAttType', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'iTControlFlagLog', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arCAcc_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'ax', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'ay', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'az', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arCAttQuat_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'q0', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'q1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'q2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'q3', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arCChannel_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'col', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'lat', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'lon', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'ped', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'fuel', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gas', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gyro', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arCPath_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'Vk', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'gamma', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'chi', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arCPos_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'dx', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'dy', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'dz', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNAcc_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'ax', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'ay', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'az', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNAirData_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'airspeed_m_s', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'baro_alt_m', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNEuler_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'phi', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'theta', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'psi', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNHeight_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'rNHeight', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'isAvailable', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'isOnGround', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNQuat_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'q0', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'q1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'q2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'q3', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNRateDot_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'pdot', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'qdot', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'rdot', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNRate_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'p', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'q', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'r', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNVelAero_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'airspeed_m_s', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'baro_alt_m', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arNVel_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'ub', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'vb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'wb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'arWGS84_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'lat_rad', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'lon_rad', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'hgt_m', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'argNPos_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'x', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'y', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'z', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'argNVel_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'ug', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'vg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'wg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'sChannelsKK', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'lat_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'lon_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'ped_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'col_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'sChannels_T', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'lat_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'lon_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'ped_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'col_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'aux1_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'aux2_us', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'sMotion', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'acc', 1, 'Bus: arNAcc_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'rate', 1, 'Bus: arNRate_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'quaternion', 1, 'Bus: arNQuat_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'pos', 1, 'Bus: argNPos_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'rate_dot', 1, 'Bus: arNRateDot_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'vel_geo', 1, 'Bus: argNVel_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'vel_body', 1, 'Bus: arNVel_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
  { ... 
    'sPilot', ... 
    '', ... 
    sprintf(''), ... 
    'Auto', ... 
    '-1', {... 
      {'sChannels', 1, 'sChannels_T', -1, 'real', 'Sample', 'Fixed', [], []}; ...
      {'eFlightMode', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], []}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
